# Configuration file
# https://github.com/connection-lost/LockettePro/wiki/*-config.yml
# If there are missing entries, you can add them manually.

language-file-name: 'lang/lang_en.yml'
enable-quick-protect: true
worldguard: true
coreprotect: true
block-interfere-placement: true
block-item-transfer-in: false
block-item-transfer-out: true
block-hopper-minecart: remove
cache-time-seconds: 0
lock-expire: false
lock-expire-days: 999
lock-default-create-time-unix: -1


# material name see: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# legacy block name and block id are not supported!
lockables:
  - MINECRAFT:DOORS
  - MINECRAFT:TRAPDOORS
  - MINECRAFT:SHULKER_BOXES
  - CHEST
  - TRAPPED_CHEST
  - BARREL
  - CHISELED_BOOKSHELF
  - DECORATED_POT
  - LECTERN
  - FURNACE
  - SMOKER
  - BLAST_FURNACE
  - HOPPER
  - DISPENSER
  - DROPPER
  - BREWING_STAND
  - JUKEBOX
  - BEACON
  - CAMPFIRES
  - MINECRAFT:ANVIL
  - DIAMOND_BLOCK
  - NETHERITE_BLOCK
  - CONDUIT
protection-exempt:
  - nothing